apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
  - targetPort: 80
    protocol: TCP
    port: 80
    nodePort: 30008
  selector:
    app: wordpress
    tier: frontend
