apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: NodePort
  ports:
    - protocol: TCP
    - targetPort: 80
    - port: 80
    - nodePort: 30008
  selector:
    app: wordpress
    tier: frontend
